poprawka workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -4,14 +4,14 @@ on: [push, workflow_dispatch]
 jobs:
   echo-hello: 
     runs-on: ubuntu-latest
-      steps:
-        - name: Say Hello
-          run: echo "Hello, World!"
+    steps:
+      - name: Say Hello
+        run: echo "Hello, World!"
   echo-goodbye:
     runs-on: ubuntu-latest
-      steps:
-        - name: Failed step
-          run: echo "I will fail"
-            exit 1
-        - name: Say Goodbye
-          run: echo "Goodbye!"
+    steps:
+      - name: Failed step
+        run: echo "I will fail"
+             exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye!"
